### ISSUE TITLE
v0.9.0 更新公告

### ISSUE THREAD

**Issue by hughfenghen** [bilibili/WebAV#103]
v0.9.0 有一些 **API 破坏性**更新，旧版本升级务必仔细阅读下面的更新文档链接。

[v0.9 更新文档](https://github.com/hughfenghen/WebAV/pull/109)

视频编辑 DEMO 预览
![image](https://github.com/hughfenghen/WebAV/assets/3307051/bf8b6ad1-7cc5-4c4d-8d09-34fb3d224a12)

**Comment by BOKE2014** [comment]
期待

**Comment by caohongz** [comment]
这个功能很棒，期待。

**Comment by xeoshow** [comment]
希望API可以支持导出帧率的参数
