### ISSUE TITLE
linux下 chrome 无法进行音频编码

### ISSUE THREAD

**Issue by xeoshow** [bilibili/WebAV#117]
rocky linux 8.8，如下图，用的自定义素材的例子，捕获不到错误。

"@webav/av-cliper": "^0.9.0-beta.13",

![image](https://github.com/hughfenghen/WebAV/assets/1164284/23cb2cb6-6250-46e5-8c37-1378333b6857)
![image](https://github.com/hughfenghen/WebAV/assets/1164284/5994d46c-fafa-4dde-8c84-35d2e55b22fe)

**Comment by xeoshow** [comment]
从错误来看，应该是对应下面代码，对应部分错误详情，没有真正展开log下来，变成了 ”id:0, **JSHandle@error**“
https://github.com/hughfenghen/WebAV/blob/75c2ef28c147d4e1ed561251c2248d1030205310/packages/av-cliper/src/combinator.ts#L79
![image](https://github.com/hughfenghen/WebAV/assets/1164284/4861f1e1-5d1e-4d64-96c8-53fdb92626e5)
![image](https://github.com/hughfenghen/WebAV/assets/1164284/16c2d84f-6dc8-4fcc-81e0-37e11ddb7abc)

**Comment by xeoshow** [comment]
这个也看到了，是一样的情况。

![image](https://github.com/hughfenghen/WebAV/assets/1164284/f396b9d5-b01d-45d6-b991-b9151c01b1e6)

**Comment by xeoshow** [comment]
经过远程调试，发现从根本上就是下面的错误：
![b5393b4c217316b550e0f4bd10b96fd](https://github.com/hughfenghen/WebAV/assets/1164284/bf33a271-8932-49b9-9e4f-8b7c560b52e7)


且由下面代码引起：
![33350bcf14ed90c1dc9dbef563b6620](https://github.com/hughfenghen/WebAV/assets/1164284/e82a0ff3-7263-4a08-b7e5-277f3c32fd42)

**Comment by xeoshow** [comment]
修改方法应该需要判断下ad是否为null或者是否已经是close，或者try catch方式？

**Comment by xeoshow** [comment]
另外，onError或onEnded暴露为event，和onProgress一样，是否更符合设计实现的一致性？

**Comment by hughfenghen** [comment]
> 经过远程调试，发现从根本上就是下面的错误： ![b5393b4c217316b550e0f4bd10b96fd](https://private-user-images.githubusercontent.com/1164284/335794351-bf33a271-8932-49b9-9e4f-8b7c560b52e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzExOTIsIm5iZiI6MTcxNzMzMDg5MiwicGF0aCI6Ii8xMTY0Mjg0LzMzNTc5NDM1MS1iZjMzYTI3MS04OTMyLTQ5YjktOWU0Zi04YjdjNTYwYjUyZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDJUMTIyMTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njg1MWFhODA4Njg2NmRkODg2NzY0NDA5MTRjMThjNzQ4MzZiM2M0OGRkNjdkY2JmYjMyZGMxM2MzMjVmNjNjOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nAYKIkwEt8qtJYw_GvpSDj--GIXZhRdbIq2n3kxX9_I)
> 
> 且由下面代码引起：
> 
> https://github.com/hughfenghen/WebAV/blob/fb8ce5066bb1609bbfe889a83c425702f2f74385/packages/av-cliper/src/mp4-utils/index.ts#L71
> 
> 
> ![33350bcf14ed90c1dc9dbef563b6620](https://private-user-images.githubusercontent.com/1164284/335794314-e82a0ff3-7263-4a08-b7e5-277f3c32fd42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzExOTIsIm5iZiI6MTcxNzMzMDg5MiwicGF0aCI6Ii8xMTY0Mjg0LzMzNTc5NDMxNC1lODJhMGZmMy03MjYzLTRhMDgtYjdlNS0yNzdmM2MzMmZkNDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDJUMTIyMTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yjk3NDc0MzFjMTZhZDhjNTQ1YzhlZGFjYmNkMjA3MTE0M2Q4MjA3ZDgyMjA1N2RmMWEwY2YwZmE3ZmQyYThkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PtcwzvSjIBMdeXnLTH9FVxKJoaIVjtx-dRafhKGREUg)

断点看看 AudioEncorder 是否正常初始化成功，是什么原因被关闭了？

**Comment by xeoshow** [comment]
代码里没有add任何Audio相关的Sprite，也有触发这个报错，感觉还是很不合理的。音频逻辑应该解耦。

**Comment by xeoshow** [comment]
![af955c4c7848a39d93c5375eafcf487](https://github.com/hughfenghen/WebAV/assets/1164284/819fc3bb-daf9-41cc-a747-b6094a32380e)

**Comment by hughfenghen** [comment]
Combinator 默认会保持音轨，即使没有音频素材。

https://github.com/hughfenghen/hughfenghen.github.io/issues/129#issuecomment-1586041964

使用这里的代码检测你的 linux chrome 是否支持 aac（mp4a.40.2）编码。

**Comment by xeoshow** [comment]
linux和windows检测是一样的，但是windows下mp3和m4a都可以正常合成，但linux都有问题
![b96f2c2ad6e96bb077c864effd3e969](https://github.com/hughfenghen/WebAV/assets/1164284/cf4427a8-d2ab-4dbb-8714-72a923b11a29)
![bd24e6f52d15a5c603eb29e4c64da42](https://github.com/hughfenghen/WebAV/assets/1164284/dcfabde4-6d22-49c2-9316-c996305cfa2a)

**Comment by xeoshow** [comment]
linux下AudioEncoder会是一上来就closed的状态
![0ab72ce75193d803342078e6ee65aad](https://github.com/bilibili/WebAV/assets/1164284/e190d7a5-0917-49a5-9ee0-3b2841dc429b)
![b85151f9e2ab72fe3fa5721c8986840](https://github.com/bilibili/WebAV/assets/1164284/12f07a5f-37ef-491f-93c2-4b3f52c03980)

**Comment by xeoshow** [comment]
![f0eba73fe1720233b94260bf0742fa9](https://github.com/bilibili/WebAV/assets/1164284/8d70e181-0436-4541-9994-363584a09992)
![4cadc8ac1863d757846ef35c979d0d6](https://github.com/bilibili/WebAV/assets/1164284/27d724fa-3e3b-4c0b-84d6-7353e6df732e)

**Comment by hughfenghen** [comment]
666，已经很接近真相了。

> 但是linux下，error事件会触发

具体抛出什么错误？请打印一下详细配置参数。

前面说 linux 通过了音频编码兼容性检测，WebAV 抛错的参数跟检测代码参数有什么区别？

**Comment by xeoshow** [comment]
linux下抛出错误是：
DOMException: Encoding error.

详细配置参数其实和windows一样，我是从webav剥离出来的：
```
const audioOpts = {
  "codec": "aac",
  "sampleRate": 48000,
  "channelCount": 2
}

const DEFAULT_AUDIO_CONF ={
  "sampleRate": 48000,
  "channelCount": 2,
  "codec": "mp4a.40.2"
}

function createAudioEncoder(){
  console.log('createAudioEncoder.in');
  const encoder = new AudioEncoder({
    error: (e) => console.error('AudioEncoder error:', e.message),
    output: (chunk, meta) => {
      console.log('createAudioEncoder.out');
    },
  });
  console.log('createAudioEncoder.out.encoder1',encoder);
  encoder.configure({
    codec: audioOpts.codec === 'aac' ? DEFAULT_AUDIO_CONF.codec : 'opus',
    sampleRate: audioOpts.sampleRate,
    numberOfChannels: audioOpts.channelCount,
    bitrate: 128_000,
  });
  console.log('createAudioEncoder.out.encoder2',encoder);
  return encoder;
}

onMounted(async () => {
  const isSupported = await Combinator.isSupported();
  console.log('Combinator.isSupported():', isSupported);
  createAudioEncoder();
});

**Comment by hughfenghen** [comment]
你去 linux chrome 控制台执行以下代码，查看打印结果
```js
const config = {
  codec: 'mp4a.40.2',
  sampleRate: 48000,
  numberOfChannels: 2,
}
console.log('AudioEncoder.isConfigSupported: ', (await AudioEncoder.isConfigSupported(config)).supported);

const encoder = new AudioEncoder({
  error: console.error,
  output: () => {}
})
encoder.configure(config)
console.log('encoder.state', encoder.state)
```

**Comment by xeoshow** [comment]
> 你去 linux chrome 控制台执行以下代码，查看打印结果
> 
> ```js
> const config = {
>   codec: 'mp4a.40.2',
>   sampleRate: 48000,
>   numberOfChannels: 2,
> }
> console.log('AudioEncoder.isConfigSupported: ', (await AudioEncoder.isConfigSupported(config)).supported);
> 
> const encoder = new AudioEncoder({
>   error: console.error,
>   output: () => {}
> })
> encoder.configure(config)
> console.log('encoder.state', encoder.state)
> ```
结果如下图所示：
![a9b705d0e8e7f2d8f1b74768a0b1d42](https://github.com/bilibili/WebAV/assets/1164284/b2fa9ba0-e257-4644-9a91-f76986d8be14)

**Comment by xeoshow** [comment]
继续调测，发现file2stream里，file.boxes数组长度为0 。。。
这里实在不太熟悉，需要如何进一步分析呢？
![21ec6ed4b0ee72ef672eba0db99d1c8](https://github.com/bilibili/WebAV/assets/1164284/cb20c08e-9fd0-4edc-8027-23b54bf807aa)
![041a47227079acea8b8805ecbad80f2](https://github.com/bilibili/WebAV/assets/1164284/3e962308-5d4c-4658-b690-6a065d408c8b)

**Comment by hughfenghen** [comment]
> > 你去 linux chrome 控制台执行以下代码，查看打印结果
> > ```js
> > const config = {
> >   codec: 'mp4a.40.2',
> >   sampleRate: 48000,
> >   numberOfChannels: 2,
> > }
> > console.log('AudioEncoder.isConfigSupported: ', (await AudioEncoder.isConfigSupported(config)).supported);
> > 
> > const encoder = new AudioEncoder({
> >   error: console.error,
> >   output: () => {}
> > })
> > encoder.configure(config)
> > console.log('encoder.state', encoder.state)
> > ```
> 
> 结果如下图所示： ![a9b705d0e8e7f2d8f1b74768a0b1d42](https://private-user-images.githubusercontent.com/1164284/336407472-b2fa9ba0-e257-4644-9a91-f76986d8be14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTc0NTgsIm5iZiI6MTcxNzQ5NzE1OCwicGF0aCI6Ii8xMTY0Mjg0LzMzNjQwNzQ3Mi1iMmZhOWJhMC1lMjU3LTQ2NDQtOWE5MS1mNzY5ODZkOGJlMTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDRUMTAzMjM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGZjYTA0OThmODE3ODNhNjI5NmViNWQ2YjdmMzRkN2M1MTBjMjYzNjU2NmQ3YzQ3MmQ4ZTgyNjEzNmJjZDgyOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1mPrtc3F7BBO6uOPBT6r7QuJPnCi-Bacm9JE9n7Wv3U)

我给的脚本代码显示，encoder 已经 创建成功了。

最后一个 `Encoding error` 是执行完脚本立即打印，还是等了一段时间才打印的错误？

是在控制台中运行我提供的代码导致的错误，还是你页面运行了其他代码导致的？

**Comment by xeoshow** [comment]
最后这个，就是运行你这个脚本时，一并出来的。和我们代码里情况本质是一致的

**Comment by hughfenghen** [comment]
ok 实锤 chrome 的 bug 了，给 chrome 提 Bug 吧。

**Comment by xeoshow** [comment]
> ok 实锤 chrome 的 bug 了，给 chrome 提 Bug 吧。
chrome版本是目前最新的，如下。 我们不需要音频，可以有什么办法先绕开这块吗？
![04e55253d44a2098a0c103954366fb5](https://github.com/bilibili/WebAV/assets/1164284/20e79057-15a2-44b7-a513-0ee6da9a8b9c)

**Comment by xeoshow** [comment]
现在合成没有加入任何音频，发现是 file.boxes.length导致return不能继续生成
![709699bd1aa88f56b673beb7213e9b1](https://github.com/bilibili/WebAV/assets/1164284/17dba8b8-b766-45e5-8c88-c164fdec5daa)

![709699bd1aa88f56b673beb7213e9b1](https://github.com/bilibili/WebAV/assets/1164284/286fd178-3ec9-4841-86e7-8b1bf85ed195)
![dbbf1bb0f0138bac4a8b4769a3c2566](https://github.com/bilibili/WebAV/assets/1164284/7f491490-7bc3-4154-b16c-d2ff340f2b57)

**Comment by hughfenghen** [comment]
> chrome版本是目前最新的，如下。 我们不需要音频，可以有什么办法先绕开这块吗？

Combinator 将开放 API 允许消音

**Comment by xeoshow** [comment]
> > chrome版本是目前最新的，如下。 我们不需要音频，可以有什么办法先绕开这块吗？
> 
> Combinator 将开放 API 允许消音

就是合成时不再介入AudioEncoder的逻辑？那这样应该就恰好可以绕开linux chrome的问题。
前面截图了file.boxes相关信息，不知是否是绕开AudioEncoder导致。

**Comment by hughfenghen** [comment]
`av-cliper@0.9.0-beta.19` 支持 Combinator 排除音轨 （audio: false）。

```js
const com = new Combinator({
  width: 1280,
  height: 720,
  videoCodec: 'avc1.42E032',
  bgColor: 'white',
  audio: false,
});
```

**Comment by xeoshow** [comment]
请教下：也可以指定audioCodec吗？类似上面的videoCodec那样

**Comment by hughfenghen** [comment]
暂时支持 audioCodec，API 从小到大谨慎开放，有必要再开放。
