### ISSUE TITLE
yarn build报错

### ISSUE THREAD

**Issue by gubeils** [bilibili/WebAV#121]
yarn install 没问题
![image](https://github.com/bilibili/WebAV/assets/102788024/83e3b29b-b91f-40c1-80c9-cd1d9ed10a1c)

构建所有 packages   yarn build会报错下面这个问题
![image](https://github.com/bilibili/WebAV/assets/102788024/fd9d908b-b215-481b-afb3-42512db1a9a0)

nodejs版本v18.16.0、win11

**Comment by hughfenghen** [comment]
![image](https://github.com/bilibili/WebAV/assets/3307051/108ccb17-3f47-4a81-a660-9cfe6cd7653e)
combinator copy.ts 是什么东西？
