### ISSUE TITLE
v1.0 更新预告

### ISSUE THREAD

**Issue by hughfenghen** [bilibili/WebAV#122]
WebAV 项目开源已经一年多，发展方向、基础能力也逐渐稳定。
v0.9 已经发布，优化了对剪辑、直播场景的支持， API 已基本稳定。

v1.0 具有里程碑意义，所以计划完成以下任务后再发布。

#298 进行中

- [x] AVCanvas 支持直播场景，输出完整的音视频流 #134
- [x] Github README 内容优化，分中英文
- [x] 优化 API 文档，核心 API 提供详细注释说明 #151 
- [x] 提供贡献文档，方便社区参与，包括：代码、站点、API 贡献
- [x] 完善 changelog 工作流，提供更好的变更日志文档
- [x] 优化 WebAV 性能，详情查看文章 [WebCodecs 性能表现及优化思路
](https://hughfenghen.github.io/posts/2024/07/27/webcodecs-performance-benchmark/)
- [x] 重新设计制作 WebAV 站点，突出 WebAV 特性，能起到宣传作用；能设计专属 ICON 最好
- [x] 所有时间参数单位统一为微秒，动画 duration（**破坏性变更**）
- [x] 重构 AVCanvas 控制点（Rect.ctrls）实现，避免同一个页面中出现多个 AVCanvas 实例时，项目影响
- [x] 回收暴露的一些不必要的工具函数（**破坏性变更**）
  - 已知要回收的函数有：
  - `decodeImg
      audioResample
      ringSliceFloat32Array
      mixinPCM
      concatFloat32Array
      concatPCMFragments
      extractPCM4AudioData
      extractPCM4AudioBuffer
      adjustAudioDataVolume
      renderTxt2Img
      createEl
      createHLSLoader
      workerTimer
      autoReadStream
      EventTool
      file2stream
      recodemux
      DEFAULT_AUDIO_CONF
      `
  - 此类都是功能单一的工具函数，如果社区有需要可考虑在新 package 中开放出来，跟 av-cliper 隔离
  - 目的：降低未来v1.0 之后出现破坏性变更的几率；让 API 文档更简洁

v1.0 发布后，会注重兼容性，只在大版本（major）发布破坏性变更，并提供迁移文档。
预计大版本最快一年发布一次。

---

在此呼吁开源贡献者、有志之士【同学/勇士/好人/金主】贡献力量，除了代码贡献外，还有以下任务需要帮助：
- WebAV 站点页面设计、 ICON 设计
- WebAV 文档、翻译

有意向请私聊我，wx：`liujun_fenghen`, 邮箱：`hughfenghen@gmail.com`；
或在评论区交流、或留下联系方式。

**Comment by chenzhutian** [comment]
加油加油, 给你多买几杯咖啡

**Comment by hughfenghen** [comment]
v1 版本已发布，https://hughfenghen.github.io/posts/2024/10/31/webav-v1-released/

**Comment by tangshanghai** [comment]
给楼主点个赞，同为web音视频开发，得向楼主多多学习
