### ISSUE TITLE
合成视频第一帧，视频内容为空，原视频第一次有内容

### ISSUE THREAD

**Issue by x007xyz** [bilibili/WebAV#123]
合成后的文件：

https://github.com/bilibili/WebAV/assets/13807549/b6a79e7c-8b3d-4ecd-bcfc-83cff711f94b

原文件：

https://github.com/bilibili/WebAV/assets/13807549/5caafd0d-df42-490c-9fd7-9d67934a0ec8

**Comment by hughfenghen** [comment]
在 0.9.0-beta.21 中修复

**Comment by x007xyz** [comment]
问题还存在，可以使用https://fly-cut.videocovert.online/重现

**Comment by x007xyz** [comment]
和视频相关，出现问题的使用 #125 的视频，使用官方demo的视频已经不存在这个问题了
