### ISSUE TITLE
合成是否考虑支持裁剪

### ISSUE THREAD

**Issue by x007xyz** [bilibili/WebAV#124]
对于音频、视频文件，合成时，可能会对文件进行裁剪（从头或者从尾部开始裁剪），现在合成视频不支持。

**Comment by hughfenghen** [comment]
试试  `IClip.split` API 
demo 中有个分割功能，https://bilibili.github.io/WebAV/demo/6_4-video-editor
一般的交互是分割后，再删掉不要的片段
