### ISSUE TITLE
合成视频时，如果视频文件比较长，报错

### ISSUE THREAD

**Issue by x007xyz** [bilibili/WebAV#125]
<img width="1500" alt="image" src="https://github.com/bilibili/WebAV/assets/13807549/b1f5d2fd-d0aa-4acf-924c-29d9bcf04e55">
报错代码
<img width="624" alt="image" src="https://github.com/bilibili/WebAV/assets/13807549/7315d47a-6b0b-4be0-a891-7cb0359ef1d1">

**Comment by hughfenghen** [comment]
请提供源文件

**Comment by hughfenghen** [comment]
无法复现，从截图中的错误看，可能跟 #126 是类似的问题。
请使用 0.9.0-beta.20  验证问题是否存在。

问题仍然存在的话，将素材压缩成 zip 给我

**Comment by x007xyz** [comment]
已验证，问题已解决
