### ISSUE TITLE
导入附件视频，然后直接导出视频，视频导出失败

### ISSUE THREAD

**Issue by kingxt** [bilibili/WebAV#126]
MP4Clip.tick timeout, {"videoReady":true,"audioReady":false}
[1716276223_cYJmNQcMYw.mp4.zip](https://github.com/user-attachments/files/15598893/1716276223_cYJmNQcMYw.mp4.zip)

**Comment by hughfenghen** [comment]
你的视频音轨采样率（sampleRate）是 22050，却标识为 44100Hz。
初始化解码器，强行改为 22050 就能正常解码合成了。

**Comment by hughfenghen** [comment]
0.9.0-beta.20 使用 DecoderSpecificInfo 中的信息来初始化解码器，兼容封装层标识错误的场景。

**Comment by busyhe** [comment]
@hughfenghen 我目前也遇到了这个问题，排除 视频文件过长、视频音轨采样率问题，因为报错不是必现。这个问题还有什么可能导致，还有什么信息我可以提供给你参考

**Comment by hughfenghen** [comment]
确保浏览器给你的页面分配足够多的计算资源。

比如
让页面置于前台，
如果处于后台 可以开一个画中画的 video，
调用新API 禁止屏幕熄屏
