### ISSUE TITLE
tick

### ISSUE THREAD

**Issue by F-howk** [bilibili/WebAV#132]
希望支持传入帧率

**Comment by F-howk** [comment]
可是recodemux 传入的帧率无效

**Comment by hughfenghen** [comment]
`expectFPS` 是传递给编码器的 期望 FPS，`recodemux` 具体帧数是你调用  `encodeVideo` 的频率决定的

**Comment by F-howk** [comment]
我试过循环 每次await tick 然后time+=1e6/60  打印time 都是相差 1e6/30
