### ISSUE TITLE
在 Rocky Linux 下使用 Google Chrome 浏览器进行视频合成时，合成进度条会一直卡在0.6 左右。虽然没有报错信息，但进度似乎无法继续。

### ISSUE THREAD

**Issue by gubeils** [bilibili/WebAV#133]
操作系统：Rocky Linux
浏览器：Google Chrome
问题概述：
1. 合成进度条在0.6 左右停止。
2. 没有报错信息或异常日志。
3. 合成过程无法正常完成。
![image](https://github.com/bilibili/WebAV/assets/102788024/ff23e191-8d92-49c0-8565-dfd879863533)
![image](https://github.com/bilibili/WebAV/assets/102788024/686626a0-f43d-4234-9c48-b6d7abe847ce)

**Comment by hughfenghen** [comment]
请提供WebAV版本、浏览器版本信息，v0.9  超市会中断流的

**Comment by gubeils** [comment]
> 请提供WebAV版本、浏览器版本信息，v0.9 超市会中断流的

"@webav/av-cliper": "^0.9.0",
Google Chrome 125.0.6422.112

**Comment by hughfenghen** [comment]
linux  chrome 存在已知问题，参考 #117

**Comment by gubeils** [comment]
> linux chrome 存在已知问题，参考 #117

可以实现一个类似onerror的事件吗，能捕捉到这个错误

**Comment by hughfenghen** [comment]
> 可以实现一个类似onerror的事件吗，能捕捉到这个错误

同意

另外，如果报错，你读取 output 返回的 stream 时能使用 try catch 捕获到异常

**Comment by gubeils** [comment]
加了try catch后没有发现报错
![image](https://github.com/bilibili/WebAV/assets/102788024/988f97eb-92b1-4921-8846-8df66702aa78)
进度条一直卡在这
![image](https://github.com/bilibili/WebAV/assets/102788024/6d3f465c-de03-4540-b77e-ffaa8806fcf3)

**Comment by hughfenghen** [comment]
[doge] 
读取流 `reader.read()` ，不是创建流

你应该参考  #117 ，使用代码检测能的浏览器，看看是否有错误信息。
或者禁用 Combinator 输出音频，看看是否能正确运行。

**Comment by gubeils** [comment]
好的，请问上面提到的onerror大概哪个版本可以好

**Comment by hughfenghen** [comment]
![image](https://github.com/bilibili/WebAV/assets/3307051/5ae63a84-0ba6-4286-b2b1-7738b2ee437c)
0.11.1   支持  error 事件
