### ISSUE TITLE
在worker 里使用mp4Clip 报错

### ISSUE THREAD

**Issue by F-howk** [bilibili/WebAV#138]
使用官方的demo都会报错

![1718675589749_54A22291-32C9-456a-88DD-F9747B436D72](https://github.com/bilibili/WebAV/assets/34292531/e9981bcc-10df-484f-b6e6-9b84a48ea304)

**Comment by hughfenghen** [comment]
更新项目代码，重新 install 升级依赖版本

**Comment by F-howk** [comment]
![image](https://github.com/bilibili/WebAV/assets/34292531/0862d818-6c11-4d03-9281-aebdde8facfe)

使用的 0.11.4

只是把这个注释解开了

![1718678544832_157D1A65-9791-4f94-B866-06F88E2FFD56](https://github.com/bilibili/WebAV/assets/34292531/155b2022-c5b2-4388-9e76-7560466ea20a)

**Comment by hughfenghen** [comment]
vite 的 bug，我给 vite 提交了 issue 与 PR https://github.com/vitejs/vite/issues/17507

**Comment by hughfenghen** [comment]
Release v0.13.10
