### ISSUE TITLE
建议：视频剪辑功能中添加文字如果增加阴影之类的效果，会超出范围被裁减掉

### ISSUE THREAD

**Issue by fangting53719** [bilibili/WebAV#139]
如题，希望能够优化这部分功能。

**Comment by hughfenghen** [comment]
请参考 #60 提供更详细的信息。

**Comment by fangting53719** [comment]
链接为demo项目修改后的，图片可以看到具体的表现和修改的代码部分，麻烦查看下，谢谢。
https://stackblitz.com/edit/m5cr78?file=src%2FApp.tsx
![image](https://github.com/bilibili/WebAV/assets/54522211/91404eee-25bc-4c9b-b73a-8603a2f5cffd)

**Comment by fangting53719** [comment]
> @fangting53719 原因是阴影内容溢出 div 盒子的边界了; 建议使用 css 策略来避免这个问题, 比如添加一个 30px 的 padding: `'font-size: 80px; color: red;text-shadow: 23px 23px 0px rgba(255, 255, 255, 0.8); padding: 30px;'`

添加padding是可以展示全了，但是可移动框体也会扩大
![image](https://github.com/bilibili/WebAV/assets/54522211/e708a671-2c5f-48ac-95cc-470524db3dba)

**Comment by hughfenghen** [comment]
这是预期之中的现象，使用 DOM 将文字转换成图片，支持 css，简单而灵活，也会有些限制。
如果 DOM 方案不能满足你的诉求，考虑使用 自定义素材 解决，参考 [DEMO](https://bilibili.github.io/WebAV/demo/2_6-custom-clip)。

**Comment by fangting53719** [comment]
> 这是预期之中的现象，使用 DOM 将文字转换成图片，支持 css，简单而灵活，也会有些限制。 如果 DOM 方案不能满足你的诉求，考虑使用 自定义素材 解决，参考 [DEMO](https://bilibili.github.io/WebAV/demo/2_6-custom-clip)。

没注意已经可以自定义Clip了，那没问题了。
