### ISSUE TITLE
使用recodemux 并且 codec 为 avc1.420034  编码的视频 无法使用 mp4clip 解码

### ISSUE THREAD

**Issue by F-howk** [bilibili/WebAV#142]
https://stackblitz.com/edit/vitejs-vite-3xkytv?file=src%2FApp.vue

按照操作就会发现控制台报错

![image](https://github.com/bilibili/WebAV/assets/34292531/767e7641-83e6-4493-a93b-bdf15c345973)

查看mdn文档后应该是codec 不符合 AVC profiles
并且recodemux 传入的 codec 和  MP4clip 解码上一次合成的codec 不一样

![image](https://github.com/bilibili/WebAV/assets/34292531/535cfd22-59bc-4edc-a0ac-7f597fd28613)

猜测： 进制转换导致的错误？ 或者codec 是需要根据具体的video来做调整？

**Comment by F-howk** [comment]
![image](https://github.com/bilibili/WebAV/assets/34292531/27756b00-ca24-4dd4-837e-282d367a4652)
改为6xx 的正常的

**Comment by hughfenghen** [comment]
`codec` 是传递给 VideoEncoder 的参数，https://developer.mozilla.org/en-US/docs/Web/API/VideoEncoder/configure
为什么解出来不一样，还没研究过。

`codec` 的类型是字符串，但取值是有一定规范的，了解更多信息需要阅读相关资料。
可以从我的文章开始：https://hughfenghen.github.io/posts/2024/05/11/webcodecs-codec-string-explain/

**Comment by F-howk** [comment]
确实原生传入的和解出来的也不一样

**Comment by hughfenghen** [comment]
查看我前面发的文档，  34（level 3.4）不在标准 H.264 Level 约定的范围内
猜测是浏览器不支持，所以自行选择了一个支持的 level
