### ISSUE TITLE
[QUESTION] Video frames on demand

### ISSUE THREAD

**Issue by jrafaaael** [bilibili/WebAV#147]
Hello there! I'm building an app where I need to get frames from a video. Right now I'm using the implementation of this repository (https://github.com/w3c/webcodecs/blob/main/samples/video-decode-display/demuxer_mp4.js) and all works fine.

However, for my web app, I don't need all frames at once; instead I prefer to get frames "on demand", by chunks (let's say chunks of 10 frames). Can I achieve something similar with this library? Any help or insaight is appreciated! Thanks in advance!

**Comment by hughfenghen** [comment]
Please refs DEMO and API.

1. [thumbnails](https://bilibili.github.io/WebAV/demo/6_1-video-thumbnails)
2. [decode video](https://bilibili.github.io/WebAV/demo/1_1-decode-video)
3. [MP4Clip.tick API](https://bilibili.github.io/WebAV/_api/av-cliper/classes/MP4Clip.html#tick)

Note: There is currently no English documentation available; it is recommended to use a translation tool or read the demo code.

**Comment by jrafaaael** [comment]
@hughfenghen thanks!

As I can see, `tick` API requires a `time` number. If I don't know the FPS from the video, how can I extract the frames sequentially?

**Comment by hughfenghen** [comment]
You can call the `tick` or `thumbnails` method with very small time steps to sequentially retrieve video frames. 

```js
// step = 10ms

for (let t = 0; ; t += 10e3) {
  const { video, state } = await mp4clip.tick(t) 
  // `video` is VideoFrame or null
  if (sate == 'done') break
}


mp4clip.thumbnails(300, { step: 10e3 })
```

Currently, there is no direct method to get video frames by number or quantity. 
Could you please explain your use case in detail?
