### ISSUE TITLE
请问可以分段解码么？

### ISSUE THREAD

**Issue by zhihaolll** [bilibili/WebAV#152]
我看了下 demo，都是通过 fetch 获取一这个完整的 mp4 视频来进行解码的，但是 fecth 是支持 range get 的

那请问下可不可以通过 fetch 获取 0-10MB 的数据，和 20-30MB 对应的数据，然后分别解码呢？ （MOOV 数据已经解析过了。

**Comment by hughfenghen** [comment]
IClip 需要的是一个 ReadableStream，你可以自行创建一个 ReadableStream 实例，就完全能控制流的数据，实现你要的功能。

```js
new MP4Clip(new ReadableStream({
  start() {
    // 实现你要的逻辑
  }
  pull() {}
}))
```

**Comment by gubeils** [comment]
大佬，我这边尝试去分段获取，将获取的ReadableStream 传递给MP4Clip，报错如下

![image](https://github.com/user-attachments/assets/d9a59e21-babf-45dd-9a10-f664eab5721e)
![image](https://github.com/user-attachments/assets/39f6f1cb-0f7b-4f70-ae6a-1474ecdc9f01)
![image](https://github.com/user-attachments/assets/12287da4-dbcb-4ecd-a620-60c856da1363)
