### ISSUE TITLE
Bug: 使用splitTrack 切分出音视频的duration不一致 

### ISSUE THREAD

**Issue by 23233** [bilibili/WebAV#175]
* version : 0.13.9
* log

![image](https://github.com/bilibili/WebAV/assets/12870070/48bb6f4b-f2b9-43eb-8e39-3cad1fbc2ad1)

![image](https://github.com/bilibili/WebAV/assets/12870070/3607cc57-5751-4832-bc79-92a356ddaf90)

**Comment by hughfenghen** [comment]
不同轨道（track）duration 不一致是正常现象。
