### ISSUE TITLE
webm转mp4

### ISSUE THREAD

**Issue by jackluson** [bilibili/WebAV#176]
录屏使用mediaRecorder得到的数据编码不支持mp4封装，使用ffmpeg转换webm to mp4 在网页端非常慢，10s webm视频转换需要6分钟，不能忍受，有办法webm直接转mp4嘛

**Comment by hughfenghen** [comment]
ffmpeg 不要重编码，转封装还是挺快的。
WebAV 暂不考虑。

**Comment by jackluson** [comment]
> ffmpeg 不要重编码，转封装还是挺快的。 WebAV 暂不考虑。

没有重编码，转出来的视频一样没办法看总时长，快进这些操作
