### ISSUE TITLE
Error: TypeError: Cannot read properties of undefined (reading 'getDirectory')

### ISSUE THREAD

**Issue by mxue12138** [bilibili/WebAV#177]
本地启动 demo 会提示这个错误，尝试切换分支，main 和 v0.11.10 都有这个问题，页面是 /demo/6_4-video-editor，进入页面后就有这个报错，然后点击 +视频 就会一直有这个报错，并且视频无法正常载入，播放器一直黑屏

mf-dep____vendor.7a12551a.async.js:60565 Uncaught (in promise) 
Error: TypeError: Cannot read properties of undefined (reading 'getDirectory')
{"cbId":1,"evtType":"register","args":{"filePath":"/.opfs-tools-temp-dir/5301398244692186-1720672502904"}}
    at e.onmessage (mf-dep____vendor.7a1….async.js:60565:153)

node v18.20.3
npm 10.7.0
pnpm 9.4.0

系统 macos(arm)
浏览器 chrome 126.0.6478.62

**Comment by hughfenghen** [comment]
本分地启动 demo，使用 localhost:port 访问

**Comment by mxue12138** [comment]
> 本分地启动 demo，使用 localhost:port 访问

已经好了，谢谢巨佬，性能很强，不过剪辑导出的码率比原视频高很多，正在研究🧐

**Comment by hughfenghen** [comment]
码率是合成视频可配置的参数，你去找找 API
