### ISSUE TITLE
视频报错 Decoding error. 没有声音

### ISSUE THREAD

**Issue by 23233** [bilibili/WebAV#178]
https://github.com/user-attachments/assets/316139fc-6b7a-47b4-b462-76866630aea0

版本:  0.13.9
视频如上 请问这是什么问题?

**Comment by 23233** [comment]
![999076fea8b06644391fcc81bd082f9](https://github.com/user-attachments/assets/56910737-4661-4ee6-bf7e-40dc15e54477)

**Comment by hughfenghen** [comment]
请基于 DEMO 提供一个可复现的小项目

**Comment by hughfenghen** [comment]
@23233   decoding error 原因是音轨编码格式：mp4a.6b
WebCodecs 不支持这个格式，请转码为 AAC LC(mp4a.40.2)

以下是 GPT 对两者的介绍

---

`mp4a.40.2` 和 `mp4a.6b` 是两种不同的音频编解码器标识，它们主要区别在于各自对应的编解码器和应用场景。

### mp4a.40.2
- **编解码器**: 这是高级音频编码 (AAC) 的标识符。
- **详细解释**: `mp4a` 表示 MPEG-4 音频，而 `40` 是对象类型标识符，表示 AAC。`2` 表示这是 AAC LC (Low Complexity) 级别。
- **应用场景**: AAC LC 是最常用的 AAC 变种，应用广泛，适用于各种多媒体应用，包括流媒体和便携设备。

### mp4a.6b
- **编解码器**: 这是 MPEG-2 的音频层 1/2 编解码器的标识符。
- **详细解释**: `mp4a` 表示 MPEG-4 音频，而 `6b` 标识的是 MPEG-2 Layer 1/2 编解码器。
- **应用场景**: MPEG-2 音频层 1/2 编解码器主要用于早期的数字电视广播和一些旧的音频压缩格式。

### 总结
- `mp4a.40.2` 是更现代的 AAC LC 编解码器，广泛应用于现代多媒体应用中，支持更高的音质和更高效的压缩。
- `mp4a.6b` 是较早期的 MPEG-2 Layer 1/2 编解码器，应用较为有限，主要用于旧的广播和音频格式。

如果你的应用需要兼容性和高质量的音频流，`mp4a.40.2` 是更好的选择。如果你需要处理老旧格式的音频，`mp4a.6b` 可能是必要的。

**Comment by tetap** [comment]
> [@23233](https://github.com/23233) decoding error 原因是音轨编码格式：mp4a.6b WebCodecs 不支持这个格式，请转码为 AAC LC(mp4a.40.2)
> 
> 以下是 GPT 对两者的介绍
> 
> `mp4a.40.2` 和 `mp4a.6b` 是两种不同的音频编解码器标识，它们主要区别在于各自对应的编解码器和应用场景。
> 
> ### mp4a.40.2
> * **编解码器**: 这是高级音频编码 (AAC) 的标识符。
> * **详细解释**: `mp4a` 表示 MPEG-4 音频，而 `40` 是对象类型标识符，表示 AAC。`2` 表示这是 AAC LC (Low Complexity) 级别。
> * **应用场景**: AAC LC 是最常用的 AAC 变种，应用广泛，适用于各种多媒体应用，包括流媒体和便携设备。
> 
> ### mp4a.6b
> * **编解码器**: 这是 MPEG-2 的音频层 1/2 编解码器的标识符。
> * **详细解释**: `mp4a` 表示 MPEG-4 音频，而 `6b` 标识的是 MPEG-2 Layer 1/2 编解码器。
> * **应用场景**: MPEG-2 音频层 1/2 编解码器主要用于早期的数字电视广播和一些旧的音频压缩格式。
> 
> ### 总结
> * `mp4a.40.2` 是更现代的 AAC LC 编解码器，广泛应用于现代多媒体应用中，支持更高的音质和更高效的压缩。
> * `mp4a.6b` 是较早期的 MPEG-2 Layer 1/2 编解码器，应用较为有限，主要用于旧的广播和音频格式。
> 
> 如果你的应用需要兼容性和高质量的音频流，`mp4a.40.2` 是更好的选择。如果你需要处理老旧格式的音频，`mp4a.6b` 可能是必要的。

你好，我遇到了一样的问题，我看了一下原视频是mp4a.40.2

[7f74663f99261fd6e5d633e83424be84.zip](https://github.com/user-attachments/files/19485550/7f74663f99261fd6e5d633e83424be84.zip)
