### ISSUE TITLE
如何降低码率

### ISSUE THREAD

**Issue by mxue12138** [bilibili/WebAV#179]
看了几遍文档，和issues，没有找到关于码率的参数，目前使用的是 OffscreenSprite+MP4Clip 实现一个在线编辑器，没有找到码率相关，求指教文档参数，我可以自己研究

**Comment by hughfenghen** [comment]
Combinator 的构造函数有个 bitrate 参数：`new Combinator({ bitrate })`

没有 export 的类型，[API](https://bilibili.github.io/WebAV/_api/av-cliper/classes/Combinator.html#constructor) 居然看不到参数详情，需要想办法优化一下。

**Comment by mxue12138** [comment]
哈哈哈哈哈，看到了，代码编辑器提示是有的，但是文档中没有显示出 Combinator 构造函数的所有参数，谢谢啦

![WechatIMG1212](https://github.com/user-attachments/assets/d4ef60c6-6295-4334-8919-2d923ec55d8a)
![QQ20240716-141912](https://github.com/user-attachments/assets/8a4558fc-7847-4222-a218-163a23a7a4ad)
