### ISSUE TITLE
Muxing/Demuxing mp4 files question

### ISSUE THREAD

**Issue by mehmetron** [bilibili/WebAV#187]
This is a really cool project.

I was reading the code, it seems you're implementing your own muxing/demuxing logic. Why not use preexisting libraries for doing this? I was just curious in case there was something I missed while reading the codebase

**Comment by hughfenghen** [comment]
WebAV use mp4box.js for muxing and demuxing.

PS: Since mp4box.js hasn't merged some bug-fixing PRs, I forked the project to ensure WebAV works properly.

https://github.com/bilibili/WebAV/blob/86586e44af1d238a69b91d1330ca3ff9561da92c/packages/av-cliper/package.json#L36

**Comment by mehmetron** [comment]
Interesting, I saw a bunch of code related to creating mp4 boxes so I assumed you implemented everything yourself. Where can I find your forked version of mp4box.js? I'd love to read over that code file

**Comment by hughfenghen** [comment]
https://github.com/hughfenghen/mp4box.js
