### ISSUE TITLE
Repeated clicking to play in DEMO will cause abnormal screen.

### ISSUE THREAD

**Issue by Yukiniro** [bilibili/WebAV#189]
1. Jump to http://localhost:8000/demo/1_1-decode-video
2. Repeated clicking 启动

https://github.com/user-attachments/assets/26fdef05-4f45-4ae9-b744-2ed6bbc75367

**Comment by hughfenghen** [comment]
@Yukiniro  Hi，这是一个已知问题，你可以帮忙修复吗？

**Comment by Yukiniro** [comment]
> @Yukiniro Hi，这是一个已知问题，你可以帮忙修复吗？

Yes, I would be happy to fix this issue.
