### ISSUE TITLE
#audioFrameFinder 引起内存泄露

### ISSUE THREAD

**Issue by wendraw** [bilibili/WebAV#195]
## 内存泄露

在给 PR https://github.com/bilibili/WebAV/pull/186 添加测试的过程中，有监听浏览器内存占用情况。发现会有内存泄露的问题：

***初步判断是 #audioFrameFinder 引起的***

内存随着时间快速膨胀，但是不会下降：

* 初始页面： <img width="1463" alt="image" src="https://github.com/user-attachments/assets/1a108ef8-680d-49ee-a104-d2a453a80a79">
* 视频播放：<img width="1243" alt="image" src="https://github.com/user-attachments/assets/b5b17276-404f-488d-bb9b-55913efd4581">
* 视频播放一段时间：<img width="1276" alt="image" src="https://github.com/user-attachments/assets/aae1e6f9-74ee-4dcd-a864-c16de1ab4b08">
* 视频播放完毕：<img width="1278" alt="image" src="https://github.com/user-attachments/assets/65df8e9f-6dc3-4c19-8702-41a1088ee958">

### performance 抓取数据
<img width="1259" alt="image" src="https://github.com/user-attachments/assets/6dec4424-b78b-45cd-b722-2697b5778fee">

### 内存快照
<img width="1259" alt="image" src="https://github.com/user-attachments/assets/ee9f3375-c980-4df3-8985-ab7b19f9abed">

### 注释掉 audioFrameFinder 代码内存占用立马降低 10+ 倍
<img width="2053" alt="image" src="https://github.com/user-attachments/assets/117ef3bc-c1b4-4c12-be29-03e7e89033b5">

**Comment by hughfenghen** [comment]
v0.14.3 优化了 audioFrameFinder 的内存占用问题，请检查一下效果

**Comment by wendraw** [comment]
🚀🚀 看起来问题似乎解决了

**解析前（887MB）**
<img width="1469" alt="image" src="https://github.com/user-attachments/assets/1e04f296-7bfa-42d5-a2d6-5cc7ab78e0b2">

**解析中（2.2GB）**
<img width="1437" alt="image" src="https://github.com/user-attachments/assets/96898563-c77a-4c9b-b8b1-bb1bc005c395">


**播放中（1.5GB）** 比较稳定
<img width="1463" alt="image" src="https://github.com/user-attachments/assets/a55f541e-8f33-4871-8af5-22af964dfad1">

**播放完（928MB）** 内存释放
<img width="1475" alt="image" src="https://github.com/user-attachments/assets/8e4aed19-cbb1-4c76-844e-7d18db89438b">


> ⚠️ 题外话，解析过程中在我的电脑上 CPU 占用比较高一直处于 300% 左右，这应该跟 web codes 无法开启硬件加速有关吧，不知道是否可以解决。
