### ISSUE TITLE
请问要如何实现视频的变速呢？

### ISSUE THREAD

**Issue by dxyloveforever** [bilibili/WebAV#200]

**Comment by hughfenghen** [comment]
1. 使用  MP4Clip 的 tickInterceptor，拦截 tick 返回的视频帧
2. 修改视频帧（VideoFrame）的时间戳，音频数据（PCM） 实现变速

WebAV 开放以上接口，支持改能力。
具体如何修改数据，需要一些音视频相关知识，比如解决变速之后的音调问题。

**Comment by caohongz** [comment]
> 1. 使用  MP4Clip 的 tickInterceptor，拦截 tick 返回的视频帧
> 2. 修改视频帧（VideoFrame）的时间戳，音频数据（PCM） 实现变速
> 
> WebAV 开放以上接口，支持改能力。 具体如何修改数据，需要一些音视频相关知识，比如解决变速之后的音调问题。

这确实是很好的方法，请问未来有可能在av-canvas中或visibleSprite中配置传入处理音视频的方法吗？目前只能通过修改av-canvas中的render方法来实现变速等操作，希望av-canvas能有更高的自由度。

**Comment by hughfenghen** [comment]
请阅读 av-canvas play 的 api，有个 playbackRate 参数

**Comment by caohongz** [comment]
> 请阅读 av-canvas play 的 api，有个 playbackRate 参数

确实看到了这个参数，但这是整体控制，会有单独控制音视频倍速的需求，另外如果能在av-canvas中有处理音频的方法就更好了。

**Comment by hughfenghen** [comment]
好的，是缺失的能力，但我目前没有时间。

你可以贡献代码实现这个功能吗。

**Comment by caohongz** [comment]
> 好的，是缺失的能力，但我目前没有时间。
> 
> 你可以贡献代码实现这个功能吗。

可以，我尝试一下

**Comment by dxyloveforever** [comment]
playbackRate只会控制视频的速度，但里面的音频实际还是原来的速度，这个有解决办法吗？

**Comment by dxyloveforever** [comment]
>这确实是很好的方法，请问未来有可能在av-canvas中或visibleSprite中配置传入处理音视频的方法吗？目前只能通过修改av-canvas中的render方法来实现变速等操作，希望av-canvas能有更高的自由度
请问能够提供部分参考代码吗？

**Comment by hughfenghen** [comment]
发布了一个快照版本，用于支持单个 Sprite 变速

目前仅支持视频、不支持音频，音频变速处理会麻烦很多，还需要开发

版本号：`0.0.0-playback-rate-20240823090827`
如果业务场景中视频可以丢弃音轨，可以试试

**Comment by foreverdxy** [comment]
期望能早日实现音频的变速

**Comment by hughfenghen** [comment]
已实现简单的音频变速

![image](https://github.com/user-attachments/assets/e87e9223-9712-4eb2-b6b0-d38840d1c6c9)
