### ISSUE TITLE
0.14.0 MP4Clip的thumbnails方法，处理大文件时报错。

### ISSUE THREAD

**Issue by nsxz945** [bilibili/WebAV#201]
升级到最新版0.14.0，MP4Clip处理大文件（初步判断应该是>2048mb，超出内存限制了）时，无法抽帧，并出现下图错误，在0.13.9是正常的。
![image](https://github.com/user-attachments/assets/2f5dbdcd-d0b7-4d36-bd75-351e6dcb55a8)

复现Demo https://stackblitz.com/edit/f5riyu-iet1xi?file=src%2FApp.tsx

**Comment by hughfenghen** [comment]
请提供具体的文件加载地址，应该跟特定文件相关。

**Comment by hughfenghen** [comment]
优化 IO 引入的 Bug，请检查  0.14.1 是否正常了。
