### ISSUE TITLE
大佬，帮忙看看，已经安装成功了@webav/av-cliper，运行时还是报错：Error: module not found: @webav/av-cliper

### ISSUE THREAD

**Issue by stevin-hong** [bilibili/WebAV#202]
我用的electron框架，在preload.js中引入：
const { avCliper } = require('@webav/av-cliper');

在之前已经安装了：
npm list @webav/av-cliper
metahuman-real@1.0.6 D:\0_projects_elctron\metahuman-real
└── @webav/av-cliper@0.14.0

node版本：18.16.0

**Comment by hughfenghen** [comment]
参考 demo 源码，使用 import 语句。

另外 avCliper 并不存在

**Comment by stevin-hong** [comment]
> 参考 demo 源码，使用 import 语句。
> 
> 另外 avCliper 并不存在

感谢大佬回复，我用import { createChromakey } from '@webav/av-cliper';方法报错，我是在electron项目中的页面中用，错误信息：

Uncaught TypeError: Failed to resolve module specifier "@webav/av-cliper". Relative references must start with either "/", "./", or "../".

根据提示改为相对路径import { createChromakey } from './node_modules/@webav/av-cliper';还是报错：

Failed to load resource: net::ERR_FILE_NOT_FOUND
