### ISSUE TITLE
对导出的视频再次导入剪辑会报错 `Unknown or ambiguous codec name.` 

### ISSUE THREAD

**Issue by 23233** [bilibili/WebAV#203]
### 复现操作步骤
* 直接去官网demo  https://bilibili.github.io/WebAV/demo/6_4-video-editor
* 拖入导出的视频

https://github.com/user-attachments/assets/97000f58-73d1-4662-85c9-d81cb04af60b

* 点击播放会直接看到报错 

### 这个导出的视频是通过 以下命令导出 未添加任何内容 并且是原素材未经过任何加工 就加入进去 然后导出 
```
await (await avCvsRef.current?.createCombinator()).output().pipeTo(output) 
```

**Comment by 23233** [comment]
![image](https://github.com/user-attachments/assets/18f55b3b-c047-4b48-8f81-2d101a6bb648)
这是官网剪辑demo的报错

**Comment by F-howk** [comment]
https://github.com/bilibili/WebAV/issues/142

**Comment by hughfenghen** [comment]
@F-howk @23233 
输出视频的 字符串编码是： avc1.420329，含义查看文档 https://hughfenghen.github.io/posts/2024/05/11/webcodecs-codec-string-explain/

constraint_set_flags 的值（03）可能是错误的，如果把二进制反转，他的值应该是 c0（avc1.42c029）

我怀疑是 chrome 的 bug，当使用不支持的编码格式创建编码器（或其他原因）
WebCodecs 输出 constraint_set_flags 二进制位弄反了

我后续有时间再验证猜想。

**Comment by hughfenghen** [comment]
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/5981b3fd-9562-4dd0-b90f-df222b1ccd2c">

卧槽，实锤 chrome 的 bug，修改了视频二进制数据，将 03 改成 C0 将正常解析了！

**Comment by hughfenghen** [comment]
Chrome 将在 **129 版本**中修复该问题，129 之前的版本升级 webav 到最新版可兼容该 bug

在 Windows、Android 系统中的 Chrome 触发了该 Bug，MacOS 系统正常
