### ISSUE TITLE
阅读源码时发现的代码错误

### ISSUE THREAD

**Issue by smileShirmy** [bilibili/WebAV#207]
main 分支，`packages/av-cliper/src/clips/mp4-clip.ts` 文件下的这个代码片段写得有问题，如果按这样写，这个 for 循环永远都不会执行了

![image](https://github.com/user-attachments/assets/b69e162e-02c4-4a14-a730-849c6f969df6)

**Comment by hughfenghen** [comment]
牛逼，居然是看代码发现的 bug。
