### ISSUE TITLE
本地运行 av-canvas 应用视频报错

### ISSUE THREAD

**Issue by Yukiniro** [bilibili/WebAV#212]
复现步骤：
- av-canvas(0.14.2) 项目执行 dev 命令
- 点击 +视频 按钮
- 抛出 Error: MP4Clip stream is done, but not emit ready at Object.onDone (mp4-clip.ts:583:18) 异常

![截屏2024-07-25 21 32 48](https://github.com/user-attachments/assets/510eb05a-ca6a-4ed7-9b00-caaac347be90)
项目中没有找到 pre-cut-11.mp4

**Comment by hughfenghen** [comment]
pri 开头的是我本地用来测试的视频文件，比较大 不方便提交到 git 仓库

**Comment by Yukiniro** [comment]
明白了，那需要改为 bunny_0 吗？还是说保持现状呢？

**Comment by hughfenghen** [comment]
你有空的话就改吧，是我调试完漏掉了，需要改回来的

**Comment by Yukiniro** [comment]
好的
