### ISSUE TITLE
代码优化

### ISSUE THREAD

**Issue by smileShirmy** [bilibili/WebAV#214]
![QQ_1721920660726](https://github.com/user-attachments/assets/5ea3b510-2e09-4d07-a378-26b8a31f8342)

上面代码等价于
```ts
const hitIndex = this.#frames.findIndex((vf) => time <= vf.timestamp)
```
这样可能看起来更容易理解

**Comment by hughfenghen** [comment]
此类问题，应该提 PR 而不是 issue
