### ISSUE TITLE
需求：期望在一个画布上只保留一个视频，当点击另一个视频的时候，会切换当前画布上的视频。同时切换的时候，会保留之前的剪辑状态

### ISSUE THREAD

**Issue by dxyloveforever** [bilibili/WebAV#219]

**Comment by hughfenghen** [comment]
参考 #60

**Comment by dxyloveforever** [comment]
useEffect(() => {
    avCvs?.on('activeSpriteChange', (sprite) => {
      if (sprite) {
        setPrevSpr(sprite);
      }
    });
  }, [avCvs,]);
  这里我会保存上一次的sprite。
  当我切换视频的时候，我将上一次保存的添加进去，但没有成功。
      try {
        setLoading(true);
        await avCvs?.addSprite(prevSprite);
      } finally {
        setLoading(false);
      }
