### ISSUE TITLE
视频的 meta 信息似乎解析有误，一个整数两秒的视频 解析后竟然是 “2033333.3333333333”

### ISSUE THREAD

**Issue by yx208** [bilibili/WebAV#221]
看起来似乎是一个浮点数问题！

WebAV 打印结果

![image](https://github.com/user-attachments/assets/0486afa6-7b81-43bb-9511-60cf2b03d618)

ffmpeg 与 Video 标签解析结果是一致的

![image](https://github.com/user-attachments/assets/544cc58c-fe2b-4657-84b6-3ee6e6d82b44)
![image](https://github.com/user-attachments/assets/31f9e35b-b69a-4201-8875-25f1e8de76c1)

**Comment by hughfenghen** [comment]
文档中有说明，时间单位是  微妙
