### ISSUE TITLE
clip.tick有些帧返回值只会是undefined

### ISSUE THREAD

**Issue by z764069592** [bilibili/WebAV#244]
下图是官网demo，在time为100000是只会是undefined，我测试了一些其他视频，都会有某些帧拿不到。
如果想获取一个视频的所有完整帧，有什么办法吗？
![screenshot-20240816-161306](https://github.com/user-attachments/assets/2da67113-6013-44cc-897a-6ae30211c127)

**Comment by hughfenghen** [comment]
@z764069592 参考缩略图 demo： https://bilibili.github.io/WebAV/demo/6_1-video-thumbnails
