### ISSUE TITLE
期望修复mp4box addTrack 的时候设置的无效矩阵信息

### ISSUE THREAD

**Issue by F-howk** [bilibili/WebAV#256]
期望编码出来的视频比较正常 没有无效矩阵信息
如果解码的时候处理了旋转信息但又没有容错机制就会出错（当然自己处理的写了的）
使用ffmpeg 也可以看到是    Side data: displaymatrix: rotation of nan degrees
解析出来是

![image](https://github.com/user-attachments/assets/2c820e8d-dbb5-4585-8d20-60683098f5b1)

在源码中找到 addTrack 发现设置的是  [ 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
![image](https://github.com/user-attachments/assets/30d58a34-ba14-47d3-8853-f0d5c39fb15d)

尝试把  .set("matrix", [0, 0, 0, 0, 0, 0, 0, 0, 0]) 改为  .set("matrix", [1 << 16, 0, 0, 0, 1 << 16, 0, 0, 0, 0x40000000])  是正常的     

有效的默认旋转信息应该是  [1 << 16, 0, 0, 0, 1 << 16, 0, 0, 0, 0x40000000]   或者   [65536, 0, 0, 0, 65536, 0, 0, 0, 1073741824]

期望使用  recodemux  编码的视频 旋转数据是有效的

**Comment by F-howk** [comment]
https://github.com/gpac/mp4box.js/issues/284

在 MP4box.js issues 中 有找到这个   但是他自己把他关了😂

**Comment by hughfenghen** [comment]
@F-howk  既然代码都写好了，可以发一个 PR 到这个项目吗？https://github.com/hughfenghen/mp4box.js

mp4box.js 不怎么更新，我 fork 一份给 WebAV 使用。

**Comment by F-howk** [comment]
为啥会有冲突啊

**Comment by gevvan** [comment]
Are you guys writing in Japanese? I don't understand! Please, is there any MP4Box -switch that can put metadata/sidedata rotation in it's MP4 output?

**Comment by F-howk** [comment]
> Are you guys writing in Japanese? I don't understand! Please, is there any MP4Box -switch that can put metadata/sidedata rotation in it's MP4 output?

First of all, it's Chinese

#235
