### ISSUE TITLE
创建MP4Clip时，无法获取到视频时长

### ISSUE THREAD

**Issue by ziiiiiiiiyan** [bilibili/WebAV#261]
如图1，能够正常创建spr并播放，但获取duration时均为0，从控制台日志可以看出，视频是可以解析出时长等信息的，但衍生创建的mp4Clip和spr等的duration均为0，请问我该如何获取到视频时长，从而配置到action的end属性中?
![46c2a266-6283-43bb-abbb-deb02ce8f784](https://github.com/user-attachments/assets/91bbfb83-902f-4edc-a202-a9078df69c16)
![1e3cbac9-5fb0-4451-93d9-136cbba497df](https://github.com/user-attachments/assets/515ef052-967f-44f4-aa82-677a2074ede4)

**Comment by caohongz** [comment]
如图，你应该是没有执行ready，所以还没有获取meta信息。
![image](https://github.com/user-attachments/assets/8c1821fd-8123-43f7-bb29-53cb0672d12b)

**Comment by ziiiiiiiiyan** [comment]
> 如图，你应该是没有执行ready，所以还没有获取meta信息。 ![image](https://private-user-images.githubusercontent.com/48698806/360340707-8c1821fd-8123-43f7-bb29-53cb0672d12b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTQ0NDcsIm5iZiI6MTcyNDMxNDE0NywicGF0aCI6Ii80ODY5ODgwNi8zNjAzNDA3MDctOGMxODIxZmQtODEyMy00M2Y3LWJiMjktNTNjYjA2NzJkMTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA4MDkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwMDM0ZjMxZGFlMzk0NTJmZWM4MjY5MGZmYzdhNDNmZWU2NGJkZmIzMTYyOGViZjc3MTNlYzQ2ZWRhYzcxM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZHwVYaQedDnkg1fi0RWscmtUfuTWmn1MARFgeghDMD8)

感谢！已解决，我给spr也执行了ready，三个都能正常获取了
![9c32be6a-e176-4cac-b85d-e8a021136cab](https://github.com/user-attachments/assets/8f57d799-d7dc-40d5-8c61-692016dd4c46)
![261f7e38-2332-4d87-94ee-385197d46c9d](https://github.com/user-attachments/assets/8eb1923f-cb8f-401e-95f6-62c084e2d25e)
