### ISSUE TITLE
生成视频关键帧缩略图可能报错

### ISSUE THREAD

**Issue by 17600482902** [bilibili/WebAV#265]
部分视频 调用关键帧缩略图报错，调查结果是thumbnailByKeyFrame里面的VideoDecoder的配置没有hardwareAcceleration，配置软解后缩略图正常生成。

**Comment by 17600482902** [comment]
![image](https://github.com/user-attachments/assets/ce6c27cd-1a78-4d9b-818a-efd04849700b)
加上好就可以解决问题，具体原因不知道，为啥解码时候加了，取关键帧缩略图没有加，可能是为了性能吧

**Comment by hughfenghen** [comment]
因为这里偷懒了，没有做解码错误自动降级软解的逻辑[doge]

**Comment by 17600482902** [comment]
视频涉密，暂时没法发哈，我继续测试一下，如果有可以的视频，发给您

**Comment by 17600482902** [comment]
我找到一个测试视频，超过10M没法在这块上传，如何给您
