### ISSUE TITLE
关于音频的变速

### ISSUE THREAD

**Issue by ErHu1993** [bilibili/WebAV#266]
你好，请问 使用 AudioClip 创建 的 VisibleSprite 如何能实现倍速播放功能？

**Comment by hughfenghen** [comment]
暂不支持，后续考虑实现

**Comment by ErHu1993** [comment]
感谢大佬；
我换了另一种方案实现了，也许能提供思路：
由JS重新生成新的带倍速音频，替换原有的 AudioClip；
带倍速的音频生成参考 [张鑫旭大佬的音频倍速](https://www.zhangxinxu.com/study/202402/js-audiobuffer-speed-pitch-keep-demo.php)

**Comment by ErHu1993** [comment]
感谢
