### ISSUE TITLE
[提问]当前MP4Clip是支持哪些格式视频的解码呢？

### ISSUE THREAD

**Issue by harukasky** [bilibili/WebAV#269]
本人现在在做一个视频剪辑工具，有用到WebAV，但是有的时候上传的视频不能够使用MP4Clip解码，会出现以下错误
![image](https://github.com/user-attachments/assets/c87f16cc-b591-432d-966d-282b183be1b9)
这是我解码失败的视频编码格式
![image](https://github.com/user-attachments/assets/59845c18-897b-4024-953b-67277e0a0ede)
但是这个编码格式的视频可以用MP4Clip进行解码
![image](https://github.com/user-attachments/assets/498a3d5c-89e8-438d-a979-3c7f110b8cf7)
能否进行解码格式的切换呢？

**Comment by hughfenghen** [comment]
可以阅读 WebCodecs API 文件，先检测是否支持视频格式。

MP4Clip 后续可以优化错误信息，抛出更详细的不兼容信息。

**Comment by harukasky** [comment]
好的，谢谢大佬，不然用ffmpeg.wasm再进行转码就太慢了
