### ISSUE TITLE
question: most efficient way to implement color correction with webav & webgl?

### ISSUE THREAD

**Issue by VaibhavGarg5M** [bilibili/WebAV#271]
Thanks for this awesome library.

I am building a real-time color correction application on videos, and was planning to use WebAV with [gl-react](https://github.com/gre/gl-react). Any recommendations would be very helpful due to your expertise in this domain.

1. What would be the most-efficient way to do this? Do I need to make any edits in av-canvas to incorporate shaders directly?
2. If I add the shaders as a sprite, would that work fine?
3. Or, I can add the shaders along directly in my react component along with the AV-canvas somehow?

Thanks once again for your work on this. I have found this library quite helpful for my video rendering use-cases. I will also be creating a PR for some potential enhancements that I made for my use-case, in couple of days.

**Comment by hughfenghen** [comment]
You might want to refer to this [DEMO](https://bilibili.github.io/WebAV/demo/3_2-chromakey-video) and the source code of the createChromakey function for additional guidance or reference.

```ts
const chromakey = createChromakey({
  // keyColor: '#00FF00'
  similarity: 0.33,
  smoothness: 0.1,
  spill: 0.1,
});
const targetClip = new MP4Clip((await fetch(resList[0])).body!);
targetClip.tickInterceptor = async (_, tickRet) => {
  if (tickRet.video == null) return tickRet;
  return {
    ...tickRet,
    video: await chromakey(tickRet.video),
  };
};
```
Tip: The key focus is on the tickInterceptor and chromakey functions.
