### ISSUE TITLE
在Chrome/108.0.5359.215 版本合成视频报错 

### ISSUE THREAD

**Issue by gubeils** [bilibili/WebAV#273]
Uncaught (in promise) Error: InvalidStateError: An operation that depends on state cached in an interface object was made but the state had changed since it was read from disk. {"cbId":1,"evtType":"register","args":{"fileId":1,"filePath":"/.opfs-tools-temp-dir/7209079213278098-1725711590313","mode":"readwrite"}}     at e.onmessage (index-CgWl-Hya.js:31:434791)
版本
  "@webav/av-cliper": "^0.14.15", 
  在electron 下的 chromium(版本：108.0.5359.215)

![image](https://github.com/user-attachments/assets/ceafd371-fd7c-4c60-b4ef-a88e8266e3bf)

**Comment by gubeils** [comment]
https://bilibili.github.io/WebAV/demo/2_1-concat-video
在electron 下的 chromium 运行官方实例demo也是一样的报错

![image](https://github.com/user-attachments/assets/d9205f63-fac8-4592-8ee1-efd8dc3e6a3f)

**Comment by gubeils** [comment]
https://hughfenghen.github.io/opfs-tools-explorer/

https://hughfenghen.github.io/opfs-tools/demo/benchmark.html

这两个链接打开运行是正常的

**Comment by hughfenghen** [comment]
参考 [chrome issue](https://issues.chromium.org/issues/41139797)

**Comment by gubeils** [comment]
> 参考 [chrome issue](https://issues.chromium.org/issues/41139797)

大佬，这个请问现在有什么解决办法吗

**Comment by hughfenghen** [comment]
查一下 Web 存储相关资料，有个 API 能获取到剩余可用的存储空间。

**Comment by gubeils** [comment]
> 查一下 Web 存储相关资料，有个 API 能获取到剩余可用的存储空间。

![image](https://github.com/user-attachments/assets/53b4262c-e377-4249-9a42-1fa6f333f549)
这个可能是chromium一个老版本的bug，实际上有剩余内存空间，bug导致获取的内存不正常，是否有可能通过别的方式绕过去？

**Comment by gubeils** [comment]
> 查一下 Web 存储相关资料，有个 API 能获取到剩余可用的存储空间。

下面这几个截图是报错的堆栈，
![image](https://github.com/user-attachments/assets/c5bb6002-42d3-46e2-aacd-dfc0d4af3e9b)

![1 1](https://github.com/user-attachments/assets/a7da540f-286e-4885-884c-4a509ba950ef)

![1 2](https://github.com/user-attachments/assets/4818ea0e-c664-4005-ba1f-035e21e6a9df)

**Comment by gubeils** [comment]
现在确定是下面这行代码报错，请问有什么办法能绕过去吗
![image](https://github.com/user-attachments/assets/0c118a6e-24ce-417d-a0c6-7d069f0d5d79)
