### ISSUE TITLE
spr.getClip()能够正确获取到mp4Clip的元信息，audioClip则不能

### ISSUE THREAD

**Issue by ziiiiiiiiyan** [bilibili/WebAV#279]
如图，在实现音视频分割的功能时，同样的代码，mp4Clip的元信息如duration能够正确获取，而audipClip的元信息错误。
已经await过
![img_v3_02en_8cbc61fc-c2d0-4735-b597-c0ffcabc911g](https://github.com/user-attachments/assets/ba7d0cc2-4f5d-45e6-bcf6-c109d28e89ca)
![img_v3_02en_6cc33991-98a8-4ba0-85d1-0cf44465df2g](https://github.com/user-attachments/assets/077c0e09-53dd-407b-88b7-03668439725c)
![img_v3_02en_ec331133-2a56-4296-b0f2-52dc0f023c9g](https://github.com/user-attachments/assets/4992b8eb-3a9a-4822-a3b9-cc0d308f07bd)

**Comment by hughfenghen** [comment]
请使用官方 demo 验证 https://bilibili.github.io/WebAV/demo/6_4-video-editor
1. 添加音频；2. 时间轴模块选中素材；3. 分割
我本地验证正常

你自己的项目需要先确认音频文件是否正常
