### ISSUE TITLE
有一些视频使用官方的demo都无法正确解析，也没有报错信息

### ISSUE THREAD

**Issue by lqomg** [bilibili/WebAV#287]
有一些视频使用官方的demo都无法正确解析，也没有报错信息。比如这个：https://drive.google.com/file/d/1K0ZFkSi2pqqTE6H6TvKeAADn3ViGCwI4/view?usp=sharing
还有就是有信息，好像是正确找到视频宽高的
https://drive.google.com/file/d/1WpHI4_44UC4eSuBHTrj8mfBs9xgRpdcj/view?usp=sharing

大佬这是咋回事儿呀

**Comment by ErHu1993** [comment]
HEVC 编码格式不支持吧

**Comment by hughfenghen** [comment]
文件内容有问题，你可以先用这个线上工具解析试试 https://gpac.github.io/mp4box.js/test/filereader.html。
WebAV 使用 mp4box.js 解封装 mp4 文件。
