### ISSUE TITLE
WebAv 只可以获取部分视频片段

### ISSUE THREAD

**Issue by easonduan1** [bilibili/WebAV#288]
我在尝试了使用WebAv以及Mp4Box.js的demo获取我想要解析的视频时,发现我总是不可以获取到完整的视频以及播放速度,我已经翻阅了相关文档,但是问题似乎还是没有解决, 我不知道该怎样用了,我把它复现了一下,如下: 

https://codesandbox.io/p/devbox/nzcpjz

有没有人可以告诉我为什么会这样?我该怎么做?这真的特别让我困扰.

这是Mp4box版: 

https://codesandbox.io/p/devbox/26plty

不知道是mp4box的问题,还是我哪里参数传的不对劲,求助!!!

**Comment by caohongz** [comment]
canvas没有设置尺寸，drawImage时传入希望渲染的尺寸，while循环执行频率很快，你需要用setInterval来控制执行速度，建议学习下相关知识。

**Comment by easonduan1** [comment]
> canvas没有设置尺寸，drawImage时传入希望渲染的尺寸，while循环执行频率很快，你需要用setInterval来控制执行速度，建议学习下相关知识。

感谢,让我去试试去!!!

**Comment by easonduan1** [comment]
> canvas没有设置尺寸，drawImage时传入希望渲染的尺寸，while循环执行频率很快，你需要用setInterval来控制执行速度，建议学习下相关知识。

太有用了, 困扰了我好久, 有没有推荐这方面的相关资料呀, 我最近对这方面特感兴趣, 可以分享下嘛,万分感谢:)

**Comment by caohongz** [comment]
> > canvas没有设置尺寸，drawImage时传入希望渲染的尺寸，while循环执行频率很快，你需要用setInterval来控制执行速度，建议学习下相关知识。
> 
> 太有用了, 困扰了我好久, 有没有推荐这方面的相关资料呀, 我最近对这方面特感兴趣, 可以分享下嘛,万分感谢:)

学习canvas相关可以看看这个：https://developer.mozilla.org/zh-CN/docs/Web/API/Canvas_API/Tutorial
