### ISSUE TITLE
反向tick耗时问题

### ISSUE THREAD

**Issue by Mng12345** [bilibili/WebAV#295]
我统计了下正向tick和反向tick，正向性能很好，都是0-20ms左右，反向的基本50-100+ms了，有什么好的优化办法吗？
![image](https://github.com/user-attachments/assets/710f2249-fa23-4118-81c4-5e5ab614441a)

**Comment by hughfenghen** [comment]
比较难、且优化空间不大。

**Comment by Mng12345** [comment]
在视频加载的时候，对视频进行解码然后倒序编码生成一个倒序的视频，针对正序和倒序视频，准备两个解码器，在tick的时候，记录下上一个tick的timestamp，如果当前tick的timestamp小于上一个tick的timestamp，就用倒序解码器解码，大于则用正序解码器解码，你看是否可行

**Comment by hughfenghen** [comment]
不可行，你可以去看看 IPB 帧、解码相关的资料。
要流畅的倒放帧，只能把已经解码的帧缓存起来，缓存帧会大幅增加显存占用。

你也许可以在倒放场景专门写代码去做优化，但这个逻辑跟 WebAV 的大部分场景冲突，所以暂不考虑支持。

**Comment by Mng12345** [comment]
好的，我看到https://clideo.com/的视频编辑器可以流畅的倒序seek，比较好奇他是怎么实现的

**Comment by tetap** [comment]
这个和视频中的I帧有关系，如果你的I帧间隙够小，倒放也是可以很流畅的。适当的可以给你的视频增加I帧解决。如果你的I帧间隔过大，那么倒放需要解码的帧间隔就越大

**Comment by Mng12345** [comment]
> 这个和视频中的I帧有关系，如果你的I帧间隙够小，倒放也是可以很流畅的。适当的可以给你的视频增加I帧解决。如果你的I帧间隔过大，那么倒放需要解码的帧间隔就越大

如果增加I帧，需要对这个视频重新编解码吧，大视频在web端挺费时间的

**Comment by hughfenghen** [comment]
WebAV 设计为了按时间顺序获取图像帧进行优化。
WebAV 反向 tick 会丢弃所有已解码的帧，重新解码、寻找当前时间需要图像帧。

所以会相对较慢，增加 I 帧解决不了这个问题。

大视频处理本身就比较耗时间，关于 WebCodecs  的性能表现 请阅读 https://hughfenghen.github.io/posts/2024/07/27/webcodecs-performance-benchmark/

**Comment by tetap** [comment]
> WebAV 设计为了按时间顺序获取图像帧进行优化。 WebAV 反向 tick 会丢弃所有已解码的帧，重新解码、寻找当前时间需要图像帧。
> 
> 所以会相对较慢，增加 I 帧解决不了这个问题。
> 
> 大视频处理本身就比较耗时间，关于 WebCodecs 的性能表现 请阅读 https://hughfenghen.github.io/posts/2024/07/27/webcodecs-performance-benchmark/

好的，了解了
