### ISSUE TITLE
音视频合成后，音频出现失帧情况（特定视频出现）

### ISSUE THREAD

**Issue by ErHu1993** [bilibili/WebAV#299]
你好，我这边发现一个无声视频在与另一个音频合成后，出现了音频部分丢帧的情况，不知道是否是视频码率导致；还是内部Bug；望博主看一下；

复现方式，使用下方资源在官网提供的视频剪辑中合成，音频需要从2秒后开始，导出视频播放出现声音卡顿；

![image](https://github.com/user-attachments/assets/89e53d09-3885-4a15-9637-f8409f02003b)

[媒体材料.zip](https://github.com/user-attachments/files/17390624/default.zip)

**Comment by Yukiniro** [comment]
这里测试了下应该跟视频没有关系，只要音频没有在起始点出现都会存在这个问题
