### ISSUE TITLE
"First sample not idr frame" error when decoding VP9-encoded mp4 files in Chrome

### ISSUE THREAD

**Issue by jrolo-ris** [bilibili/WebAV#303]
Hello,

I've encountered an issue when using WebAV to decode and display an MP4 file encoded with VP9. The console logs the following error:

```
First sample not idr frame
```

This issue occurs both in my project and in the official demo found at this link: [WebAV Video Decode Demo](https://bilibili.github.io/WebAV/demo/1_1-decode-video).

**Steps to Reproduce:**
1. Navigate to the [WebAV video decoding demo](https://bilibili.github.io/WebAV/demo/1_1-decode-video).
2. Select the `bear.mp4` file.
3. Attempt to play the file.
4. Observe the console error in Chrome.

**Environment:**
- Chrome Version: 129.0.6668.103
- File format: MP4 encoded with VP9

**Expected Behavior:**
The file should decode and play without errors.

**Actual Behavior:**
The file does not play correctly, and the console logs the error: `First sample not idr frame`.

I noticed there might be a related pull request (#301), but after manually building from that branch and testing it, I encountered the same error. 

Has anyone been able to get VP9 video working successfully? Any guidance would be greatly appreciated!

Thank you!

**Comment by jrolo-ris** [comment]
I must have made a mistake building PR #301. When I copied the library into my project imported directly from the unbuilt ./src/av-cliper/src/clips/mp4-clip.ts it now works as expected.

**Comment by hughfenghen** [comment]
Fixed in v0.16.4
