### ISSUE TITLE
使用视频剪辑Demo时，视频无法显示画面，合成出来的视频页面没有画面

### ISSUE THREAD

**Issue by x007xyz** [bilibili/WebAV#306]
提示警告：hook.js:608 First sample not idr frame

第一帧确认是关键帧

![image](https://github.com/user-attachments/assets/d8df8df3-7095-4cc3-af8b-f24493a83de3)
![image](https://github.com/user-attachments/assets/dd40e1bb-d4a9-4a17-8783-5b128e0785c7)

视频文件：
https://fly-cut.oss-cn-hangzhou.aliyuncs.com/%E4%B8%8B%E8%BD%BD%20%286%29.mp4

**Comment by hughfenghen** [comment]
少写了一个类型，近期修复

参考 ffmpeg  `IS_IDR(s)   ((s)->nal_unit_type == NAL_IDR_W_RADL \|\| (s)->nal_unit_type == NAL_IDR_N_LP)`
https://ffmpeg.org/doxygen/2.6/libavcodec_2hevc_8h.html#a0149bdce65c87e9ccee137eb54502019a5115fdfc109c53df56954e6c77ea2630
