### ISSUE TITLE
clip 裁切拼合之后，播放视频会出现黑色闪屏

### ISSUE THREAD

**Issue by youyidevs** [bilibili/WebAV#308]
复现例子：
官方的视频剪辑 demo https://bilibili.github.io/WebAV/demo/6_4-video-editor
多裁切几次播放可能就出现黑屏效果，
如下是简化之后必复现的例子：
https://stackblitz.com/edit/llhnbb?file=src%2FApp.tsx

**Comment by hughfenghen** [comment]
在 v1.0.0 版本修复

**Comment by youyidevs** [comment]
嗯，更新到 1.0 之后，黑屏比原来少了 但还是有。上面的例子，在播放到 11s 左右的时候还是会黑屏 貌似这个黑屏的时间还变长了
======
是不是 用第几帧第几帧而不是第几秒第几秒来截取更合理些呢？

**Comment by hughfenghen** [comment]
切割时  分割点判断有个小 bug。

按 帧 切割不适用于音频。
