### ISSUE TITLE
解码视频拿到的sample渲染到canvas上发现清晰度降低了

### ISSUE THREAD

**Issue by lq199612** [bilibili/WebAV#309]
![01](https://github.com/user-attachments/assets/568081ce-0978-434c-a931-7d3c621aa9e7)
这是直接使用video播放视频的画面
![02](https://github.com/user-attachments/assets/31a86516-4354-4336-b14b-03714f4cf4b0)
这是解码视频拿到的sample渲染到canvas的画面
前后对面，发现清晰度降低了，这是为什么

**Comment by hughfenghen** [comment]
https://www.cnblogs.com/moqiutao/p/16439373.html

可能是高清屏引发的问题

**Comment by xeoshow** [comment]
文章总结得很全面
