### ISSUE TITLE
visible property of class Offscreensprite not work

### ISSUE THREAD

**Issue by mhy-max** [bilibili/WebAV#310]
https://stackblitz.com/edit/yy5ecs?file=src%2FApp.tsx

**Comment by hughfenghen** [comment]
`visible` 仅能用于 `VisibleSprite`，用在 `OffscreenSprite` 中没有意义，如果不想展示 `OffscreenSprite`  不要添加该 Sprite 即可。

设计上有点问题，应该把 `visible` 字段放在 `VisibleSprite` 上，将在 v1 版本将移 `OffscreenSprite.visible` 字段定义。
