### ISSUE TITLE
videoFrame 传递到 IClip 的 tick 方法中使用？

### ISSUE THREAD

**Issue by gubeils** [bilibili/WebAV#315]
因为业务逻辑复杂 ，不能像下面的示例代码在tick里创建videoFrame，只能在 IClip 的 tick 方法之外创建 videoFrame。
如何能将这个 videoFrame 传递到 IClip 的 tick 方法中使用？

或者，当有新的 videoFrame 可用时，希望可以触发 tick 方法，而不是依赖 tick 方法的定时调用机制。这可以使 IClip 在每次 videoFrame 更新时立即执行相关处理，而不需要等待 tick 调用的时间间隔。

https://bilibili.github.io/WebAV/demo/2_6-custom-clip

![image](https://github.com/user-attachments/assets/5210fa89-5cec-4eed-ba34-df1b92d88cd5)

**Comment by hughfenghen** [comment]
tick 是一个 异步（async）函数，你可以 await 一个 Promise，在你的图像帧生成之后再 resolve。
