### ISSUE TITLE
Combinator 是否能支持如下参数

### ISSUE THREAD

**Issue by gubeils** [bilibili/WebAV#319]
latencyMode: 'realtime',
    // 添加以下质量参数
    avc: {
      format: 'annexb',
      profile: 'high',
      level: '4.0',
      bitDepth: 8,
      hardwareAcceleration: 'prefer-hardware',
    },
    // 控制编码质量
    encoderConfig: {
      bitrateMode: 'constant', // 或 'variable'
      complexity: 'balanced', // 可选 'quality'/'speed'
      quality: 100, // 1-100,越高质量越好
    },
![image](https://github.com/user-attachments/assets/9db30ef0-3e64-45ca-a8fb-38c36428f360)

**Comment by hughfenghen** [comment]
#60

**Comment by hughfenghen** [comment]
建议先阅读 WebCodecs API 文档
