### ISSUE TITLE
Deepin V23 Chrome 130 文档首页的项目提示不兼容

### ISSUE THREAD

**Issue by lb091188** [bilibili/WebAV#320]
![image](https://github.com/user-attachments/assets/72bdd9c3-a314-4b81-bb10-5953255b051a)
![image](https://github.com/user-attachments/assets/844673f4-9496-43c1-a5e6-9537bd9b7bdf)

**Comment by hughfenghen** [comment]
什么型号的 CPU、GPU？

换 Edge 试试。
