### ISSUE TITLE
解码能否指定某个时间区间进行解码

### ISSUE THREAD

**Issue by tetap** [bilibili/WebAV#327]
现在整个文件的加载会非常消耗内存。比如我一个视频轨道可能只需要截取第5秒–第10秒，但是不得不加载整个文件。这点不知道能否优化

**Comment by hughfenghen** [comment]
MP4Clip 设计用于剪辑场景，所以需要加载整个文件。

如果你想使用 MP4Clip 解码文件， 只要其中部分片段而不想加载其余部分，
需要自行写代码从 CDN 下载所需片段的内容，组装成文件流或存储到 OPFS，再提供给 MP4Clip。

**Comment by tetap** [comment]
> MP4Clip 设计用于剪辑场景，所以需要加载整个文件。
> 
> 如果你想使用 MP4Clip 解码文件， 只要其中部分片段而不想加载其余部分， 需要自行写代码从 CDN 下载所需片段的内容，组装成文件流或存储到 OPFS，再提供给 MP4Clip。

了解了，我的意思其实也是用于剪辑场景。当一个视频从剪辑轨道缩减时长和扩充时长，这部分内存如果可以释放的话，我觉得是合理的。我正在研究，谢谢

**Comment by hughfenghen** [comment]
剪辑状态，视频文件的绝大部分数据在磁盘中，不会全部加载到内存。 参考 #129 

> 现在整个文件的加载会非常消耗内存

如果发现异常，请使用官方 demo 复现并反馈 bug。

**Comment by gubeils** [comment]
请问现在这个有什么进展吗，我现在也是用的MP4Clip，发现gpu占用很大，是否可以做到分段加载？

**Comment by tetap** [comment]
> 请问现在这个有什么进展吗，我现在也是用的MP4Clip，发现gpu占用很大，是否可以做到分段加载？

gpu占用高是正常的，视频解码本身是高消耗。只是我要解决的内存的占用
