### ISSUE TITLE
[Question]  error  in ./node_modules/@webav/av-canvas/dist/av-canvas.js

### ISSUE THREAD

**Issue by luliloveshe918** [bilibili/WebAV#333]
我使用的vue，引入av-canvas， 实现最简单的播放demo。但是出现编译报错. 我查找资料，好像是Webpack的问题，我尝试按照chatgpt说的方案，还是不成功。现有的项目可能使用的版本较低，但是遗留问题，也不能随意升级。
我想问的是，有什么简单方式，能否把现有av-canvas引入到我的这个项目
报错信息、示例代码、部分package.json以及chatgpt分析原因如下截图：
![475a99127b70f04cb47b91120a4328d1](https://github.com/user-attachments/assets/94962b5b-b1a5-44ca-9acf-ad90cec3ca75)
![9c7225d37da594a955727b9250d02764](https://github.com/user-attachments/assets/3d386a73-8536-48fa-beb3-a07eac1fdfc5)
![28df7fa008ce58b371e9fb14235e41d2](https://github.com/user-attachments/assets/6628e7b9-9f0d-465c-a809-3e8175baa1bb)
![f6aca7278f1935f6e74465d8df660c67](https://github.com/user-attachments/assets/d633d28c-3413-4740-9178-08246c21d995)

**Comment by luliloveshe918** [comment]
webAV使用的"typescript": "^5.4.5", 我的项目使用的"typescript": "~4.5.2",

**Comment by caohongz** [comment]
可以尝试下@babel/plugin-proposal-nullish-coalescing-operator，并在babel.config.js配置该插件
可以参考文章：https://blog.csdn.net/qq_43363884/article/details/116429278

**Comment by luliloveshe918** [comment]
问题解决了！ 
尝试1：babel.config.js添加插件，不成功
![d34021275e72b314c8b0dc90c7ab3d2b](https://github.com/user-attachments/assets/4f84fb18-dddb-4aaf-baf3-b07107a20be2)
尝试2：vue.config.js添加 node_modules转换的包， 成功
参考文档链接：https://blog.csdn.net/sinat_31213021/article/details/134813401
![e6890fe548df82dba8772e25a5c10457](https://github.com/user-attachments/assets/c3d8f61b-b9ef-4c27-8dfc-8b897bfda50a)
