### ISSUE TITLE
[Bug] 在webworker里引入MP4Clip后报错ReferenceError: localStorage is not defined

### ISSUE THREAD

**Issue by gubeils** [bilibili/WebAV#334]
能否在webworker里支持使用MP4Clip？
![image](https://github.com/user-attachments/assets/5f448fc7-d376-43c5-9045-0a7673ae36a3)
![image](https://github.com/user-attachments/assets/015a7629-2a43-4bd1-b7d1-c44239dc176c)

**Comment by hughfenghen** [comment]
#60

**Comment by gubeils** [comment]
升级到最新版发现这两个有问题，IClip,concatAudioClip,其他正常
![image](https://github.com/user-attachments/assets/a619279f-d1bc-40c2-b46d-b0a031ef1712)
