### ISSUE TITLE
[Question] 怎样实现两个视频的混合，即2个视频帧的混合模式

### ISSUE THREAD

**Issue by luliloveshe918** [bilibili/WebAV#337]
类似剪映的功能：
一、有2个视频
       视频1：前景视频（鸽子飞舞）
       视频2：背景视频（广场宣传片）
二、前景视频设置混合模式
       正常、滤色、柔光、正片叠底等
三、视频预览与合成是混合后的效果
       鸽子在广场飞舞

混合的算法我自己写，只是预览视频与合成时，需要有个方法，入参是这2个视频的帧，返回值是混合模式计算后的帧。不知道webAV是否提供这个方法或者其他实现方式。

这是典型的是视频混合，不是单个视频帧的处理，是需要获得多个视频帧数据、经过计算、输出一个结果视频帧

前景视频
![20fd38b89d8d899bba1c8101380e47b8](https://github.com/user-attachments/assets/de1afaa8-1682-43e3-87d1-e1819566144c)
背景视频
![d6d0a5e8ff5be5eea0263db0acab21fe](https://github.com/user-attachments/assets/0a312f99-d6e2-4bc0-abf4-1e96bbb04542)
混合后视频
![d95347676b6c381ab9a710f34eb5f572](https://github.com/user-attachments/assets/e048ab8a-015f-4397-9761-da67c91770d7)

**Comment by hughfenghen** [comment]
参考文档  进阶篇： https://bilibili.github.io/WebAV/guide/advanced

**Comment by luliloveshe918** [comment]
> 参考文档 进阶篇： https://bilibili.github.io/WebAV/guide/advanced
> 
> 另外，看你的截图，这个项目已经很成熟了，外部用户可以体验吗

1、这个截图是剪映pc版，为了直观一点表达我需要实现的效果。
2、看了进阶篇，拦截器只是拦截一个视频得帧输出，tick时刻拦截， 而我需要的是2个视频的帧混合计算。

**Comment by hughfenghen** [comment]
创建一个自定义素材（实现 IClip 接口），将两个视频素材（MP4Clip）合并输出为一个

**Comment by luliloveshe918** [comment]
那这样和实际素材数量不匹配了吧。比如我就2个视频素材，为了实现这个混合模式多加一个素材类型，素材总数变为3.
我看了webav渲染源码，貌似逻辑是:
1、遍历所有素材，
    1-1、tick帧(拦截器)
    1-2、帧绘制到1个canvas上
2、编码canvas
如果在1-1、tick帧(拦截器)后，把帧都保存起来，加一步逻辑“所有帧处理”，然后再绘制到canvas上，是否可行呢

**Comment by hughfenghen** [comment]
目前没有计划支持该能力，但我同意你的场景是 WebAV 需要解决的问题。
实现的方案与细节需要讨论，欢迎你的 RFC 与 PR。

**Comment by luliloveshe918** [comment]
> 那这样和实际素材数量不匹配了吧。比如我就2个视频素材，为了实现这个混合模式多加一个素材类型，素材总数变为3. 我看了webav渲染源码，貌似逻辑是: 1、遍历所有素材， 1-1、tick帧(拦截器) 1-2、帧绘制到1个canvas上 2、编码canvas 如果在1-1、tick帧(拦截器)后，把帧都保存起来，加一步逻辑“所有帧处理”，然后再绘制到canvas上，是否可行呢

貌似只有这样，才能实现特效（下雪、浓雾等）、转场

**Comment by Dramalf** [comment]
你可以用[react-gl-transition](https://github.com/gre/gl-transition-libs)，将你需要添加专场的两个视频单独绘制到一个canvas上，再作为节点插入到全局canvas上
