### ISSUE TITLE
[Bug] createChromakey在webWorker引入报错

### ISSUE THREAD

**Issue by gubeils** [bilibili/WebAV#338]
在webworker里引入createChromakey报错

![image](https://github.com/user-attachments/assets/68f2afab-727b-41f5-9efa-0241545a7d57)
![image](https://github.com/user-attachments/assets/00185170-2d81-476c-a89f-45fbc7cca2e9)

**Comment by hughfenghen** [comment]
请参考 #60  并按模板提供必要信息，否则该 issue 将被关闭
