### ISSUE TITLE
[Feature] BaseSprite或visibleSprite 是否可以默认有一个id 或可以注入的metaData之类的吗?

### ISSUE THREAD

**Issue by 23233** [bilibili/WebAV#342]
**背景/功能描述**

目前选中visibleSprite 很难定位到是timeline中的哪一个 因为没有任何的唯一标识 

**解决方案**

默认增加一个唯一标识 或可自定义数据挂载到BaseSprite中

**Comment by hughfenghen** [comment]
本来是有一个 name 标识的，但这 sdk 内部几乎没有作用，所以废弃了。
如果业务场景需要，你可以给 VisibleSprite 扩展 一个 id 属性用于标识。

```ts
interface ExtVisibleSprite extends VisibleSprite { id: string } 
```

如果你想给 sprite 关联某些数据，建议使用 Map 数据结构 `Map<VisibleSprite, YOUR_DATA_TYPE>`
