### ISSUE TITLE
[Question] 请教大佬,一个mp4clip如何重复播放 loop?

### ISSUE THREAD

**Issue by 23233** [bilibili/WebAV#345]
**问题描述**

如何让一个原本只有10分钟的视频,设置duration为60分钟,然后一直重复loop画面呢?

**您尝试过的解决办法**

我看到audio有loop 但是没看到mp4Clip有loop行为的行为

**Comment by hughfenghen** [comment]
参考官方的播放 demo 实现播放，再循环传给 tick 的时间参数即可。
