### ISSUE TITLE
[Question] 继承mp4clip 但是在合成视频时候会执行clone 而clone中直接指向的mp4clip 导致合成时未继承

### ISSUE THREAD

**Issue by 23233** [bilibili/WebAV#347]
**问题描述**

因为mp4clip使用了很多内部方法 而我想要自定义tick方法实现 视频的loop效果和一些特效的混合 
当我尝试完全实现一个mp4clip较为复杂 因为里面使用了大量的内部的未导出的方法 
在预览的时候tick可以自定义覆盖掉 但是在合成的时候 会有一个clone而这个clone是直接指向了mp4clip 
https://github.com/bilibili/WebAV/blob/main/packages/av-cliper/src/clips/mp4-clip.ts#L352
https://github.com/bilibili/WebAV/blob/main/packages/av-cliper/src/combinator.ts#L156C5-L156C36 

**您尝试过的解决办法**

尝试自己定义一个mp4clip 但是内部有大量未导出的方法 牵连很广 无从下手 

**想要达到的效果**
可以继承内置的几个clip 并且可以自定义tick方法 当然入参和出参保持不变 只是内部执行逻辑可以自定义 方便制作特效混合 更灵活

最后感谢大佬..

**Comment by hughfenghen** [comment]
你可以继承 MP4Clip, 覆盖 tick clone 等方法的实现。

你不可能去修改内部逻辑，只能通过继承覆盖、扩展。
