### ISSUE TITLE
关于大文件剪辑

### ISSUE THREAD

**Issue by pbdm** [bilibili/WebAV#82]
期望通过 和 https://github.com/hughfenghen/opfs-tools 配合，避免内存占用过多

**Comment by hughfenghen** [comment]
v0.9 以优化内存占用

**Comment by itzhoujun** [comment]
@hughfenghen 请问下使用 mp4clip使用了opfs存储，有做清理吗？会不会导致硬盘占用越来越大

**Comment by hughfenghen** [comment]
tmpfile 创建的文件三天有效期，后续访问会自动清理过期文件；
或者你可以自己控制文件（file），自定义清理逻辑
