### ISSUE TITLE
测试官方在线演示例子，生成的视频有卡顿情况

### ISSUE THREAD

**Issue by xeoshow** [bilibili/WebAV#96]
看了最新在线部署的官方例子，还是有和下面issue(已经关闭)的同样问题：
https://github.com/hughfenghen/WebAV/issues/75

因为官方示例即可重现（用上个工单提供的那些输入文件和材料信息等），所以无需再提供针对性的其他的最小化代码项目例子。

**Comment by hughfenghen** [comment]
请提供 @webav/av-cliper 离屏快速合成视频，可复现卡顿的项目（codecssandbox）

**Comment by xeoshow** [comment]
并不需要提供这种复现卡顿的项目，因为直接用官方例子实测就能复现的，即官方例子就有这个issue提到的问题。
官方例子是下面这个链接，用#75提供的素材直接就能复现了：
https://hughfenghen.github.io/WebAV/demo/4_2-recorder-avcanvas

**Comment by hughfenghen** [comment]
https://bilibili.github.io/WebAV/demo/4_2-recorder-avcanvas

重写了 AVCanvas、AVRecorder，我本地使用你的素材录制正常，请验证确认问题是否还存在。

**Comment by xeoshow** [comment]
用同样素材试了下，比之前好不少，但貌似还是偶尔略微轻微卡顿。请看附件。
https://github.com/bilibili/WebAV/assets/1164284/902bb699-abe2-4384-b64f-37065008b363

**Comment by hughfenghen** [comment]
我看效果还行，起始阶段卡了一下。

AVCanvas 录制视频偶现卡顿在预期之中，在直播场景偶然丢帧是能接受的。
素材合成场景，请使用 Combinator，更快更稳定。

如果没有请他问题，将关闭该 issue

**Comment by xeoshow** [comment]
没问题，确实很好了。
就是直播流是否也可以封装一个 Clip类 在AVCliper模块？这样可以方便和自己定制化的Canvas搭配协同。相信这是一个普适场景。

**Comment by hughfenghen** [comment]
v0.10.0  已经实现： `MediaStreamClip`；
另外在剪辑场景 `AVCanvas.createCombinator` API 可以快速将用户添加、排版编辑的素材转为 `Combinator` 对象，用于快速导出视频，具体情参考 [DEMO](https://bilibili.github.io/WebAV/demo/6_4-video-editor)。

提示：`MediaStreamClip` 是**实时流**，无法应用于 `Combinator` 中加速合成视频。
